const Action = {
  COMMAND_PROCESSED: 'COMMAND_PROCESSED',
  RENDERER_LOADED: 'RENDERER_LOADED',
  SET_BASE: 'SET_BASE',
  SYSTEM_LOADING: 'SYSTEM_LOADING'
}

const ConnectionStatus = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED'
}

export { Action, ConnectionStatus }
