const Action = {
  COMMAND_PROCESSED: 'COMMAND_PROCESSED',
  RENDERER_LOADED: 'RENDERER_LOADED',
  SET_BASE: 'SET_BASE',
  SYSTEM_LOADED: 'SYSTEM_LOADED',
  SYSTEM_LOADING: 'SYSTEM_LOADING'
}

export { Action }
