const Action = {
  COMMAND_EXECUTED: 'COMMAND_EXECUTED',
  EVALUATE_INPUT: 'EVALUATE_INPUT',
  PLUGIN_LOADED: 'PLUGIN_LOADED',
  SYSTEM_LOADED: 'SYSTEM_LOADED',
  SYSTEM_LOADING: 'SYSTEM_LOADING'
}

export { Action }
